[phases.setup]
nixPkgs = ["sqlite"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input"]

[start]
cmd = "gunicorn ong_backend.wsgi:application --bind 0.0.0.0:$PORT"

