[phases.setup]
nixPkgs = ["python311", "sqlite"]
aptPkgs = ["sqlite3", "libsqlite3-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
  "chmod +x start.sh",
  "python manage.py collectstatic --no-input"
]

[start]
cmd = "./start.sh"