[phases.setup]
nixPkgs = ["sqlite"]
aptPkgs = ["sqlite3", "libsqlite3-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input"]

[start]
cmd = "sh -c 'gunicorn ong_backend.wsgi:application --bind 0.0.0.0:${PORT:-8000}'"