[phases.setup]
nixPkgs = ["sqlite"]
aptPkgs = ["sqlite3", "libsqlite3-dev"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input"]